# Generated by Django 5.2.3 on 2025-06-28 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=12, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("isin", models.CharField(blank=True, max_length=16, null=True)),
                ("country", models.CharField(blank=True, max_length=32, null=True)),
                ("sector", models.CharField(blank=True, max_length=64, null=True)),
                ("industry", models.CharField(blank=True, max_length=64, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open", models.DecimalField(decimal_places=4, max_digits=12)),
                ("close", models.DecimalField(decimal_places=4, max_digits=12)),
                ("high", models.DecimalField(decimal_places=4, max_digits=12)),
                ("low", models.DecimalField(decimal_places=4, max_digits=12)),
                ("volume", models.BigIntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="portfolio.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("company", "date")},
            },
        ),
    ]
